### ISSUE TITLE
silent failure on 10kdiabetes file?

### ISSUE THREAD

**Issue by tom-dyar** [evshvarov/csvgen#5] opened 2020-09-28 21:23 UTC
[10kdiabetes_small.zip](https://github.com/evshvarov/csvgen/files/5295128/10kdiabetes_small.zip)

This file is failing import with csvgen, no output, so perhaps some warning/error printing could be added wherever it is failing? I am running a prerelease version of IRIS and I just installed csvgen via zpm...

**Comment by tom-dyar** [comment] 2020-09-28 23:16
the problem is the "." in the column names, which we should indicate as a limitation somewhere in the documentation, and then a warning/error should be printed out, IMO.

**Comment by evshvarov** [comment] 2020-09-29 06:20
Maybe let’s just filter dots from col names?

вт, 29 сент. 2020 г. в 02:16, Thomas Dyar <notifications@github.com>:

**Comment by evshvarov** [comment] 2020-09-29 19:09
I made it return errors now with a new release. I mentioned the limitation in "Known issues" - and the problem is that system ##class(%SQL.Util.Procedures).CSVTOCLASS() method I use doesn't allow dots in columns.

**Comment by tom-dyar** [comment] 2020-09-29 19:12
Cool, I will try to check it out, thanks!!

**Comment by evshvarov** [comment] 2020-09-29 19:22
BTW, try [csvgen-ui](https://openexchange.intersystems.com/package/csvgen-ui) - great tool!
<img width="468" alt="Screenshot 2020-09-29 at 22 20 57" src="https://user-images.githubusercontent.com/2781759/94605754-39a4ef00-02a2-11eb-9701-1d36c50f0aec.png">
<img width="468" alt="Screenshot 2020-09-29 at 22 22 36" src="https://user-images.githubusercontent.com/2781759/94605823-4de8ec00-02a2-11eb-92ee-f3449a27a8a8.png">

**Comment by evshvarov** [comment] 2020-10-17 09:50
Hi @tom-dyar ! This is fixed with 1.1.10 [release](https://openexchange.intersystems.com/package/csvgen?tab=history).

**Closed as completed by evshvarov** 2020-10-17 09:50 UTC
